// Generates the button icons: resources/drawables/icons/*.svg,
// resources/drawables/icons.xml and source/Icons.mc, all from the ICONS
// table below. Run after changing it:  node tools/gen-icons.mjs
//
// Only buttons WITHOUT a conventional written form get an icon (DEL, BACK,
// unit categories, dice, tip, ...). Digits, operators (+ - × ÷ % =), math
// notation (sin, log, x², √, π, M+, ...) and unit/currency codes stay text -
// that IS their standard notation, an icon would be less readable, not more.
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ICON_H = 8; // icon height, % of screen (smallest button is ~11%)
const WHITE = '#FFFFFF';

// Pictograms on a 24x24 box. d = stroked path; dots = filled [x,y,r];
// rings = stroked [x,y,r].
const ICONS = [
  ['del', 'back', { d: 'M8 5 L21 5 L21 19 L8 19 L2 12 Z M11.5 9 L17 15 M17 9 L11.5 15' }],
  ['back', [], { d: 'M9 6 L3 12 L9 18 M3 12 L14 12 Q20 12 20 6' }],
  ['adv', 'adv', { d: 'M6 6 L12 12 L6 18 M13 6 L19 12 L13 18' }],
  ['units', 'units', { d: 'M4 8 L18 8 M14 4 L18 8 L14 12 M20 16 L6 16 M10 12 L6 16 L10 20' }],
  ['dice', ['random', 'randGen'], { d: 'M4 4 L20 4 L20 20 L4 20 Z', dots: [[8.5, 8.5, 1.7], [12, 12, 1.7], [15.5, 15.5, 1.7]] }],
  ['tip', 'tip', { d: 'M5 3 L19 3 L19 21 L16.7 19.5 L14.3 21 L12 19.5 L9.7 21 L7.3 19.5 L5 21 Z M9 15.5 L15 6.5', rings: [[9.3, 8, 1.4], [14.7, 14, 1.4]] }],
  ['cat_dist', 'cat:dist', { d: 'M3 16 L16 3 L21 8 L8 21 Z M7 12 L9 14 M10 9 L12.5 11.5 M13 6 L15 8' }],
  ['cat_weight', 'cat:weight', { d: 'M7 9 L17 9 L20 21 L4 21 Z M9 9 Q9 4 12 4 Q15 4 15 9' }],
  ['cat_temp', 'cat:temp', { d: 'M10 14.8 L10 5 Q10 3 12 3 Q14 3 14 5 L14 14.8 M12 9 L12 15.5', rings: [[12, 18, 3.3]] }],
  ['cat_speed', 'cat:speed', { d: 'M3.5 17.5 A9 9 0 1 1 20.5 17.5 M12 15 L16.5 8.5', dots: [[12, 15, 1.8]] }],
  ['cat_pace', 'cat:pace', { d: 'M12 14 L12 9.5 M10 3 L14 3 M12 3 L12 6.5 M18 6.5 L19.5 5', rings: [[12, 14, 7.5]] }],
  ['cat_vol', 'cat:vol', { d: 'M6 3 L18 3 L16.5 21 L7.5 21 Z M6.7 10 L17.3 10' }],
  ['cat_area', 'cat:area', { d: 'M4 4 L20 4 L20 20 L4 20 Z M4 12 L12 4 M4 20 L20 4 M12 20 L20 12' }],
  ['cat_time', 'cat:time', { d: 'M12 7 L12 12 L16 14', rings: [[12, 12, 9]] }],
  ['cat_pres', 'cat:pres', { d: 'M12 3 L12 13.5 M8 9.5 L12 13.5 L16 9.5 M4 17.5 L20 17.5 M4 21 L20 21' }],
  ['cat_energy', 'cat:energy', { d: 'M13 2 L5 14 L11 14 L10 22 L19 9 L13 9 Z' }],
  ['cat_cur', 'cat:cur', { d: 'M15 8.5 Q14 7 12 7 Q9 7 9 9.5 Q9 11.5 12 12 Q15 12.5 15 14.5 Q15 17 12 17 Q10 17 9 15.5 M12 5 L12 19', rings: [[12, 12, 9.5]] }],
  ['other', 'curOther', { d: 'M14.5 14.5 L20.5 20.5', rings: [[10, 10, 6]] }],
  ['again', 'randAgain', { d: 'M19 12 A7 7 0 1 1 16.9 7.1 M17.5 2.5 L17.5 7.5 L12.5 7.5' }],
  ['plus', ['randNewRange', 'tipNew'], { d: 'M12 4 L12 20 M4 12 L20 12' }],
  ['next', ['randNext', 'tipNext'], { d: 'M4 12 L19 12 M13 6 L19 12 L13 18' }],
  ['go', 'tipGo', { d: 'M4 12.5 L9.5 18 L20 6' }],
];

const r = (n) => +n.toFixed(2);

function svg(icon) {
  let body = `<path d="${icon.d}"/>`;
  for (const [x, y, rad = 1.7] of icon.dots ?? []) body += `<circle cx="${x}" cy="${y}" r="${rad}" fill="${WHITE}" stroke="none"/>`;
  for (const [x, y, rad] of icon.rings ?? []) body += `<circle cx="${x}" cy="${y}" r="${rad}"/>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">` +
    `<g fill="none" stroke="${WHITE}" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">${body}</g></svg>\n`;
}

const iconDir = join(root, 'resources', 'drawables', 'icons');
rmSync(iconDir, { recursive: true, force: true });
mkdirSync(iconDir, { recursive: true });

let xml = '<!-- Generated by tools/gen-icons.mjs - do not edit by hand. -->\n<resources>\n';
const entries = [];
for (const [name, actions, icon] of ICONS) {
  writeFileSync(join(iconDir, `${name}.svg`), svg(icon));
  // Icons here are all a 1:1 (24x24) box, so scaleX == scaleY.
  xml += `    <bitmap id="ic_${name}" filename="icons/${name}.svg" scaleX="${ICON_H}%" scaleY="${ICON_H}%" dithering="none"/>\n`;
  for (const a of [actions].flat()) entries.push(`        "${a}" => Rez.Drawables.ic_${name},`);
}
xml += '</resources>\n';
writeFileSync(join(root, 'resources', 'drawables', 'icons.xml'), xml);

writeFileSync(join(root, 'source', 'Icons.mc'), `import Toybox.Lang;

// Generated by tools/gen-icons.mjs - do not edit by hand.
// Icon resource for a button, or null to draw its text label instead.
// Only buttons without a conventional written form get an icon here -
// digits, operators, math notation and unit/currency codes stay text.
function iconFor(action as String, label as String) as ResourceId? {
    if (label.equals("BACK")) {
        return Rez.Drawables.ic_back;
    }
    var ids = {
${entries.join('\n')}
    };
    return ids[action];
}
`);
console.log(`${ICONS.length} icons generated`);
