import Toybox.Lang;

// Generated by tools/gen-icons.mjs - do not edit by hand.
// Icon resource for a button, or null to draw its text label instead.
// Only buttons without a conventional written form get an icon here -
// digits, operators, math notation and unit/currency codes stay text.
function iconFor(action as String, label as String) as ResourceId? {
    if (label.equals("BACK")) {
        return Rez.Drawables.ic_back;
    }
    var ids = {
        "back" => Rez.Drawables.ic_del,
        "adv" => Rez.Drawables.ic_adv,
        "units" => Rez.Drawables.ic_units,
        "random" => Rez.Drawables.ic_dice,
        "randGen" => Rez.Drawables.ic_dice,
        "tip" => Rez.Drawables.ic_tip,
        "cat:dist" => Rez.Drawables.ic_cat_dist,
        "cat:weight" => Rez.Drawables.ic_cat_weight,
        "cat:temp" => Rez.Drawables.ic_cat_temp,
        "cat:speed" => Rez.Drawables.ic_cat_speed,
        "cat:pace" => Rez.Drawables.ic_cat_pace,
        "cat:vol" => Rez.Drawables.ic_cat_vol,
        "cat:area" => Rez.Drawables.ic_cat_area,
        "cat:time" => Rez.Drawables.ic_cat_time,
        "cat:pres" => Rez.Drawables.ic_cat_pres,
        "cat:energy" => Rez.Drawables.ic_cat_energy,
        "cat:cur" => Rez.Drawables.ic_cat_cur,
        "curOther" => Rez.Drawables.ic_other,
        "randAgain" => Rez.Drawables.ic_again,
        "randNewRange" => Rez.Drawables.ic_plus,
        "tipNew" => Rez.Drawables.ic_plus,
        "randNext" => Rez.Drawables.ic_next,
        "tipNext" => Rez.Drawables.ic_next,
        "tipGo" => Rez.Drawables.ic_go,
    };
    return ids[action];
}
