import Toybox.Lang;

// Generated by tools/gen-icons.mjs - do not edit by hand.
// Icon resource for a button, or null to draw its text label instead.
// Only buttons without a conventional written form get an icon here -
// digits, operators, math notation and unit/currency codes stay text.

// No formulaCat:*/formulas entries or their icons - FORMULAS isn't
// reachable on these watches (see moreButtons() in calc-for-garminView.mc).
function iconFor(action as String, label as String) as ResourceId? {
    var idx = label.equals("BACK") ? ["1"] as Array<String>? :
        specLookup(",back~0,adv~2,units~3,random~4,randGen~4,tip~5,cat:dist~6,cat:weight~7,cat:temp~8,cat:speed~9,cat:pace~10,cat:vol~11,cat:area~12,cat:time~13,cat:pres~14,cat:energy~15,cat:cur~16,curOther~17,randAgain~18,randNewRange~19,tipNew~19,randNext~20,tipNext~20,tipGo~21,curLeft~22,curRight~23,const:π~24,", action);
    if (idx == null) {
        return null;
    }
    return [
        Rez.Drawables.ic_del,
        Rez.Drawables.ic_back,
        Rez.Drawables.ic_adv,
        Rez.Drawables.ic_units,
        Rez.Drawables.ic_dice,
        Rez.Drawables.ic_tip,
        Rez.Drawables.ic_cat_dist,
        Rez.Drawables.ic_cat_weight,
        Rez.Drawables.ic_cat_temp,
        Rez.Drawables.ic_cat_speed,
        Rez.Drawables.ic_cat_pace,
        Rez.Drawables.ic_cat_vol,
        Rez.Drawables.ic_cat_area,
        Rez.Drawables.ic_cat_time,
        Rez.Drawables.ic_cat_pres,
        Rez.Drawables.ic_cat_energy,
        Rez.Drawables.ic_cat_cur,
        Rez.Drawables.ic_other,
        Rez.Drawables.ic_again,
        Rez.Drawables.ic_plus,
        Rez.Drawables.ic_next,
        Rez.Drawables.ic_go,
        Rez.Drawables.ic_larr,
        Rez.Drawables.ic_rarr,
        Rez.Drawables.ic_pi
    ][idx[0].toNumber() as Number] as ResourceId;
}
